/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as IaRouteImport } from './routes/ia'
import { Route as FluxosRouteImport } from './routes/fluxos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as IndexRouteImport } from './routes/index'

const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosRoute = FluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxos': typeof FluxosRoute
  '/ia': typeof IaRoute
  '/projetos': typeof ProjetosRoute
  '/prompts': typeof PromptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxos': typeof FluxosRoute
  '/ia': typeof IaRoute
  '/projetos': typeof ProjetosRoute
  '/prompts': typeof PromptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentes': typeof AgentesRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fluxos': typeof FluxosRoute
  '/ia': typeof IaRoute
  '/projetos': typeof ProjetosRoute
  '/prompts': typeof PromptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentes'
    | '/chat'
    | '/configuracoes'
    | '/fluxos'
    | '/ia'
    | '/projetos'
    | '/prompts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentes'
    | '/chat'
    | '/configuracoes'
    | '/fluxos'
    | '/ia'
    | '/projetos'
    | '/prompts'
  id:
    | '__root__'
    | '/'
    | '/agentes'
    | '/chat'
    | '/configuracoes'
    | '/fluxos'
    | '/ia'
    | '/projetos'
    | '/prompts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentesRoute: typeof AgentesRoute
  ChatRoute: typeof ChatRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FluxosRoute: typeof FluxosRoute
  IaRoute: typeof IaRoute
  ProjetosRoute: typeof ProjetosRoute
  PromptsRoute: typeof PromptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos': {
      id: '/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof FluxosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentesRoute: AgentesRoute,
  ChatRoute: ChatRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FluxosRoute: FluxosRoute,
  IaRoute: IaRoute,
  ProjetosRoute: ProjetosRoute,
  PromptsRoute: PromptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
